# Generated by Django 5.0.3 on 2025-12-04 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionCanal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('canal', models.CharField(max_length=20)),
                ('estado_envio', models.CharField(default='pendiente', max_length=20)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificacion_canal',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('modulo', models.CharField(max_length=50)),
                ('referencia_id', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'db_table': 'notificacion',
                'ordering': ['-order_date'],
            },
        ),
    ]
