# Generated by Django 5.0.3 on 2026-01-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='link',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='url_destino',
            field=models.CharField(blank=True, help_text='Link al hacer clic', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('info', 'Información'), ('exito', 'Éxito'), ('alerta', 'Alerta'), ('error', 'Error')], default='info', max_length=20),
        ),
    ]
