# Generated by Django 5.0.3 on 2025-12-04 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel', models.CharField(blank=True, help_text='Ej: Junior, Senior, C-Level', max_length=50, null=True)),
                ('banda_salarial_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('banda_salarial_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puestos', to='core.empresa')),
            ],
            options={
                'db_table': 'puesto',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(help_text='DNI/Cédula/Pasaporte', max_length=20)),
                ('email', models.EmailField(help_text='Correo corporativo único', max_length=150, unique=True)),
                ('foto_url', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('baja', 'Baja'), ('licencia', 'Licencia')], default='activo', max_length=20)),
                ('zona_horaria', models.CharField(blank=True, max_length=50, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='core.empresa')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='empleados.empleado')),
                ('unidad_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='core.unidadorganizacional')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='empleados.puesto')),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(help_text='Ej: Indefinido, Plazo Fijo', max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='NULL si es Indefinido', null=True)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jornada_semanal_horas', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('documento_url', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('finalizado', 'Finalizado'), ('anulado', 'Anulado')], default='vigente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='asistencia.turno')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='empleados.empleado')),
            ],
            options={
                'db_table': 'contrato',
                'indexes': [models.Index(fields=['empleado', 'estado'], name='contrato_emplead_1734b2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.UniqueConstraint(fields=('empresa', 'cedula'), name='unique_empresa_cedula'),
        ),
    ]
