# Generated by Django 5.0.3 on 2025-12-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_remove_empleado_foto_url_empleado_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Licencia', 'Licencia'), ('Suspendido', 'Suspendido')], default='Activo', max_length=20),
        ),
    ]
