# Generated by Django 5.0.3 on 2026-01-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_empleado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='dias_laborales',
            field=models.CharField(default='Lunes a Viernes', help_text='Texto informativo para el dashboard', max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='hora_entrada_teorica',
            field=models.TimeField(default='09:00', help_text='Hora esperada de entrada'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='hora_salida_teorica',
            field=models.TimeField(default='18:00', help_text='Hora esperada de salida'),
        ),
    ]
