# Generated by Django 5.0.3 on 2026-01-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_empleado_dias_laborales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dias_laborales',
            field=models.CharField(default='LUN,MAR,MIE,JUE,VIE', help_text='Lista de códigos de días laborales separados por comas', max_length=50),
        ),
    ]
