# Generated by Django 5.0.3 on 2026-01-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_empleado_dias_laborales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contrato',
        ),
    ]
