# Generated by Django 5.0.3 on 2026-01-11 08:52

import core.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_delete_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Indefinido', 'Tiempo Indefinido'), ('Plazo Fijo', 'Plazo Fijo'), ('Obra', 'Por Obra o Servicio'), ('Eventual', 'Eventual / Pasantía')], max_length=50)),
                ('cargo_en_contrato', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('archivo_pdf', models.FileField(blank=True, null=True, storage=core.storage.PrivateMediaStorage(), upload_to='contratos/%Y/', verbose_name='PDF Firmado')),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Es contrato vigente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='empleados.empleado')),
            ],
        ),
    ]
