# Generated by Django 5.0.3 on 2026-01-17 17:49

import core.storage
import empleados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, storage=core.storage.PrivateMediaStorage(), upload_to=empleados.models.ruta_contrato_dinamica, verbose_name='PDF Firmado'),
        ),
    ]
