# Generated by Django 5.0.3 on 2025-12-04 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('razon_social', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('pais', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=2, null=True)),
                ('moneda', models.CharField(blank=True, help_text='ISO 4217', max_length=3, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('zona_horaria', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='UnidadOrganizacional',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, help_text="Ej: 'Sucursal', 'Departamento', 'Filial'", max_length=50, null=True)),
                ('ubicacion', models.CharField(blank=True, help_text='Dirección física o descripción', max_length=255, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='core.empresa')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='core.unidadorganizacional')),
            ],
            options={
                'db_table': 'unidad_organizacional',
            },
        ),
    ]
