# Generated by Django 5.0.3 on 2026-01-10 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracionErp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: SAP HANA, Oracle Netsuite', max_length=50)),
                ('url_api', models.URLField(help_text='Endpoint principal del sistema externo')),
                ('api_key', models.CharField(help_text='Token de autenticación', max_length=255)),
                ('usuario_api', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ultima_sincronizacion', models.DateTimeField(blank=True, null=True)),
                ('estado_sincronizacion', models.CharField(choices=[('ok', 'Exitoso'), ('error', 'Error')], default='ok', max_length=20)),
            ],
            options={
                'verbose_name': 'Configuración ERP',
                'verbose_name_plural': 'Integraciones ERP',
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Notificar a Slack RRHH', max_length=100)),
                ('evento', models.CharField(choices=[('empleado_creado', 'Nuevo Empleado'), ('solicitud_aprobada', 'Vacaciones Aprobadas'), ('alerta_kpi', 'Alerta de KPI Bajo')], max_length=50)),
                ('url_destino', models.URLField(help_text='URL donde se enviará el POST')),
                ('secret_key', models.CharField(blank=True, help_text='Para firmar el payload', max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('intentos_fallidos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LogIntegracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('codigo_respuesta', models.IntegerField(help_text='Ej: 200, 404, 500')),
                ('mensaje_respuesta', models.TextField(blank=True)),
                ('integracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integraciones.integracionerp')),
                ('webhook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integraciones.webhook')),
            ],
        ),
    ]
