# Generated by Django 5.0.3 on 2025-12-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAsistencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('check_in', 'Entrada'), ('check_out', 'Salida'), ('pausa_in', 'Inicio Pausa'), ('pausa_out', 'Fin Pausa')], max_length=20)),
                ('registrado_el', models.DateTimeField(help_text='Fecha hora servidor')),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('precision_gps', models.IntegerField(blank=True, help_text='Metros de error', null=True)),
                ('foto_url', models.TextField(blank=True, null=True)),
                ('origen', models.CharField(blank=True, help_text='app, web, biometrico', max_length=20, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'evento_asistencia',
            },
        ),
        migrations.CreateModel(
            name='JornadaCalculada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_primera_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_ultima_salida', models.DateTimeField(blank=True, null=True)),
                ('minutos_trabajados', models.IntegerField(default=0)),
                ('minutos_tardanza', models.IntegerField(default=0)),
                ('minutos_extra', models.IntegerField(default=0)),
                ('estado', models.CharField(default='incompleto', help_text='completo, incompleto, ausente', max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jornada_calculada',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tolerancia_minutos', models.IntegerField(default=0)),
                ('tiempo_comida_minutos', models.IntegerField(default=60)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'turno',
            },
        ),
    ]
