# Generated by Django 5.0.3 on 2025-12-04 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
        ('core', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoasistencia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcaciones', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='jornadacalculada',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='turno',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddIndex(
            model_name='eventoasistencia',
            index=models.Index(fields=['empleado', 'registrado_el'], name='evento_asis_emplead_91d67d_idx'),
        ),
        migrations.AddConstraint(
            model_name='jornadacalculada',
            constraint=models.UniqueConstraint(fields=('empleado', 'fecha'), name='unique_jornada_diaria'),
        ),
    ]
