# Generated by Django 5.0.3 on 2026-01-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornadacalculada',
            name='estado',
            field=models.CharField(choices=[('puntual', 'Puntual'), ('atraso', 'Atraso'), ('falta', 'Falta'), ('permiso', 'Permiso'), ('incompleto', 'Incompleto'), ('libre', 'Día Libre')], default='falta', help_text='Estado calculado para el dashboard', max_length=20),
        ),
    ]
