# Generated by Django 5.0.3 on 2025-12-04 02:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('porcentaje_avance', models.IntegerField(default=0)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
            ],
            options={
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='ActividadEmpleado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(default='ejecutor', max_length=50)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.actividad')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
            ],
            options={
                'db_table': 'actividad_empleado',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='ejecutores',
            field=models.ManyToManyField(related_name='actividades', through='poa.ActividadEmpleado', to='empleados.empleado'),
        ),
        migrations.CreateModel(
            name='MetaEmpleado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(default='colaborador', max_length=50)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
            ],
            options={
                'db_table': 'meta_empleado',
            },
        ),
        migrations.CreateModel(
            name='MetaTactico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('indicador', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_esperado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_actual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('equipo', models.ManyToManyField(related_name='metas', through='poa.MetaEmpleado', to='empleados.empleado')),
            ],
            options={
                'db_table': 'meta',
            },
        ),
        migrations.AddField(
            model_name='metaempleado',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.metatactico'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='poa.metatactico'),
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('anio', models.IntegerField(help_text='Año fiscal (ej: 2025)')),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'db_table': 'objetivo',
            },
        ),
        migrations.AddField(
            model_name='metatactico',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_tacticas', to='poa.objetivo'),
        ),
        migrations.CreateModel(
            name='ObjetivoEmpleado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(default='lider', help_text='lider, co-lider, stakeholder', max_length=50)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poa.objetivo')),
            ],
            options={
                'db_table': 'objetivo_empleado',
            },
        ),
        migrations.AddField(
            model_name='objetivo',
            name='equipo',
            field=models.ManyToManyField(related_name='objetivos', through='poa.ObjetivoEmpleado', to='empleados.empleado'),
        ),
        migrations.AddConstraint(
            model_name='actividadempleado',
            constraint=models.UniqueConstraint(fields=('actividad', 'empleado'), name='unique_actividad_ejecutor'),
        ),
        migrations.AddConstraint(
            model_name='metaempleado',
            constraint=models.UniqueConstraint(fields=('meta', 'empleado'), name='unique_meta_miembro'),
        ),
        migrations.AddConstraint(
            model_name='objetivoempleado',
            constraint=models.UniqueConstraint(fields=('objetivo', 'empleado'), name='unique_objetivo_miembro'),
        ),
    ]
