# Generated by Django 5.0.3 on 2026-01-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='metatactico',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('cumplida', 'Cumplida'), ('vencida', 'Vencida')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado'), ('archivado', 'Archivado')], default='activo', max_length=20),
        ),
    ]
