# Generated by Django 5.0.3 on 2026-01-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0002_alter_actividad_estado_alter_metatactico_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatactico',
            name='valor_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='metatactico',
            name='valor_esperado',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
    ]
