# Generated by Django 5.0.3 on 2025-12-04 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(help_text='%, USD, Puntos', max_length=20)),
                ('frecuencia', models.CharField(help_text='mensual, trimestral', max_length=20)),
                ('formula', models.TextField(blank=True, null=True)),
                ('meta_default', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'db_table': 'kpi',
            },
        ),
        migrations.CreateModel(
            name='KPIResultado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(help_text='Ej: 2025-11', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meta_periodo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calculado_automatico', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='kpi.kpi')),
            ],
            options={
                'db_table': 'kpi_resultado',
            },
        ),
        migrations.AddConstraint(
            model_name='kpiresultado',
            constraint=models.UniqueConstraint(fields=('kpi', 'empleado', 'periodo'), name='unique_kpi_periodo'),
        ),
    ]
