# Generated by Django 5.0.3 on 2026-01-07 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_empleado_dias_laborales'),
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpi',
            options={'verbose_name': 'KPI', 'verbose_name_plural': 'KPIs'},
        ),
        migrations.RemoveConstraint(
            model_name='kpiresultado',
            name='unique_kpi_periodo',
        ),
        migrations.AlterField(
            model_name='kpi',
            name='frecuencia',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='unidad_medida',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='kpiresultado',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_resultados', to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='kpiresultado',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='kpi.kpi'),
        ),
        migrations.AlterField(
            model_name='kpiresultado',
            name='periodo',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='kpiresultado',
            constraint=models.UniqueConstraint(fields=('kpi', 'empleado', 'periodo'), name='unique_kpi_periodo_empleado'),
        ),
    ]
