# Generated by Django 5.0.3 on 2026-01-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_alter_kpi_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpiresultado',
            options={'ordering': ['-periodo']},
        ),
        migrations.RemoveConstraint(
            model_name='kpiresultado',
            name='unique_kpi_periodo_empleado',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='kpiresultado',
            name='empleado',
        ),
        migrations.AddField(
            model_name='kpi',
            name='codigo',
            field=models.CharField(choices=[('HEADCOUNT', 'Total Empleados'), ('AUSENTISMO', 'Ausentismo Laboral'), ('PUNTUALIDAD', 'Puntualidad'), ('ROTACION', 'Rotación de Personal'), ('SALARIO_PROM', 'Salario Promedio'), ('MANUAL', 'Ingreso Manual')], default='MANUAL', help_text='Determina la lógica de cálculo automático', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='kpiresultado',
            constraint=models.UniqueConstraint(fields=('kpi', 'periodo'), name='unique_kpi_periodo'),
        ),
    ]
