# Generated by Django 5.0.3 on 2026-01-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_alter_kpiresultado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='codigo',
            field=models.CharField(choices=[('HEADCOUNT', 'Total Empleados'), ('AUSENTISMO', 'Ausentismo Laboral'), ('ROTACION', 'Rotación de Personal'), ('PUNTUALIDAD', 'Puntualidad'), ('SALARIO_PROM', 'Salario Promedio'), ('MANUAL', 'Ingreso Manual')], default='MANUAL', help_text='Determina la lógica de cálculo automático', max_length=50),
        ),
    ]
