# Generated by Django 5.0.3 on 2025-12-04 02:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroVacaciones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(help_text='Ciclo fiscal', max_length=20)),
                ('dias_asignados', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dias_tomados', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('dias_disponibles', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_vacaciones', to='empleados.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'db_table': 'registro_vacaciones',
            },
        ),
        migrations.CreateModel(
            name='SolicitudAusencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_habiles', models.DecimalField(decimal_places=2, max_digits=5)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('adjunto_url', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='empleados.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'db_table': 'solicitud_ausencia',
            },
        ),
        migrations.CreateModel(
            name='AprobacionAusencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(help_text='aprobar, rechazar', max_length=20)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('aprobador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='solicitudes.solicitudausencia')),
            ],
            options={
                'db_table': 'aprobacion_ausencia',
            },
        ),
        migrations.CreateModel(
            name='TipoAusencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('afecta_sueldo', models.BooleanField(default=False)),
                ('requiere_documento', models.BooleanField(default=False)),
                ('descuenta_vacaciones', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'db_table': 'ausencia',
            },
        ),
        migrations.AddField(
            model_name='solicitudausencia',
            name='ausencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitudes.tipoausencia'),
        ),
        migrations.AddConstraint(
            model_name='registrovacaciones',
            constraint=models.UniqueConstraint(fields=('empleado', 'periodo'), name='unique_saldo_periodo'),
        ),
    ]
