# Generated by Django 5.0.3 on 2025-12-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobacionausencia',
            name='accion',
            field=models.CharField(choices=[('aprobar', 'Aprobar'), ('rechazar', 'Rechazar')], default='aprobar', help_text='Aprobar o rechazar la solicitud', max_length=20),
        ),
    ]
