# Generated by Django 5.0.3 on 2025-12-08 03:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_aprobacionausencia_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobacionausencia',
            name='fecha_accion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
