# Generated by Django 5.0.3 on 2025-12-18 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_empleado_estado'),
        ('solicitudes', '0003_alter_aprobacionausencia_fecha_accion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registrovacaciones',
            name='unique_saldo_periodo',
        ),
        migrations.RemoveField(
            model_name='registrovacaciones',
            name='dias_disponibles',
        ),
        migrations.AddField(
            model_name='solicitudausencia',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aprobacionausencia',
            name='accion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='aprobacionausencia',
            name='fecha_accion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='aprobacionausencia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registrovacaciones',
            name='dias_asignados',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='registrovacaciones',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='registrovacaciones',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registrovacaciones',
            name='periodo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='adjunto_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='dias_habiles',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('devuelto', 'Devuelto (Subsanar)')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipoausencia',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipoausencia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='aprobacionausencia',
            table=None,
        ),
        migrations.AlterModelTable(
            name='registrovacaciones',
            table=None,
        ),
        migrations.AlterModelTable(
            name='solicitudausencia',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tipoausencia',
            table=None,
        ),
    ]
