# Generated by Django 5.0.3 on 2026-01-17 20:25

import core.storage
import solicitudes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_remove_registrovacaciones_unique_saldo_periodo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudausencia',
            name='adjunto_url',
        ),
        migrations.AddField(
            model_name='solicitudausencia',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, storage=core.storage.PrivateMediaStorage(), upload_to=solicitudes.models.ruta_adjunto_solicitud, verbose_name='Documento de Soporte'),
        ),
    ]
