# Generated by Django 5.0.3 on 2026-01-17 21:44

import core.storage
import django.db.models.deletion
import solicitudes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_remove_solicitudausencia_adjunto_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudausencia',
            name='archivo_adjunto',
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='dias_habiles',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AdjuntoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(storage=core.storage.PrivateMediaStorage(), upload_to=solicitudes.models.ruta_adjunto_solicitud, verbose_name='Documento')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='solicitudes.solicitudausencia')),
            ],
        ),
    ]
